# Standards: 0.1
---
- name: Fact tunnelblick user
  set_fact:
    tunnelblick_user: "{{ tunnelblick_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - tunnelblick

- name: Create global directory
  loop: "{{ tunnelblick_global_configs }}"
  loop_control:
    label: "{{ item.name }}"
  file:
    path: "/Library/Application Support/Tunnelblick/Shared/{{ item.name }}.tblk/Contents/Resources"
    state: directory
    owner: root
    group: wheel
    mode: u=rwx,g=rx,o=rx
  tags:
    - tunnelblick

- name: Write global config
  loop: "{{ tunnelblick_global_configs }}"
  loop_control:
    label: "{{ item.name }}"
  template:
    src: config.j2
    dest: "/Library/Application Support/Tunnelblick/Shared/{{ item.name }}.tblk/Contents/Resources/config.ovpn"
    owner: root
    group: wheel
    mode: u=rwx,g=,o=
  tags:
    - tunnelblick

- become: "{{ (tunnelblick_user != ansible_user_id) | bool }}"
  become_user: "{{ tunnelblick_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: tunnelblick
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - tunnelblick

    - name: Remove quarantine flag
      register: tunnelblick_quarantine
      failed_when: tunnelblick_quarantine.rc != 0 and "No such xattr" not in tunnelblick_quarantine.stderr
      changed_when: tunnelblick_quarantine.rc == 0
      command: xattr -d com.apple.quarantine /Applications/Tunnelblick.app
      tags:
        - tunnelblick

    - name: Create local directory
      loop: "{{ tunnelblick_local_configs }}"
      loop_control:
        label: "{{ item.name }}"
      notify:
        - Kill tunnelblick
        - Start tunnelblick
      file:
        path: "/Users/{{ tunnelblick_user }}/Library/Application Support/Tunnelblick/Configurations/{{ item.name }}.tblk/Contents/Resources"
        state: directory
        owner: "{{ tunnelblick_user }}"
        group: staff
        mode: u=rwx,g=rx,o=
      tags:
        - tunnelblick

    - name: Write local config
      loop: "{{ tunnelblick_local_configs }}"
      loop_control:
        label: "{{ item.name }}"
      notify:
        - Kill tunnelblick
        - Start tunnelblick
      template:
        src: config.j2
        dest: "/Users/{{ tunnelblick_user }}/Library/Application Support/Tunnelblick/Configurations/{{ item.name }}.tblk/Contents/Resources/config.ovpn"
        owner: "{{ tunnelblick_user }}"
        group: staff
        mode: u=rwx,g=r,o=
      tags:
        - tunnelblick

    - name: Has launched before
      notify:
        - Kill tunnelblick
        - Start tunnelblick
      osx_defaults:
        domain: net.tunnelblick.tunnelblick
        key: SUHasLaunchedBefore
        type: bool
        value: True
        state: present
      tags:
        - tunnelblick

    - name: Enable automatic checks
      notify:
        - Kill tunnelblick
        - Start tunnelblick
      osx_defaults:
        domain: net.tunnelblick.tunnelblick
        key: SUEnableAutomaticChecks
        type: bool
        value: "{{ tunnelblick_enable_automatic_checks }}"
        state: present
      tags:
        - tunnelblick

    - name: Launch next login
      notify:
        - Kill tunnelblick
        - Start tunnelblick
      osx_defaults:
        domain: net.tunnelblick.tunnelblick
        key: launchAtNextLogin
        type: bool
        value: '{{ tunnelblick_launch_at_next_login }}'
        state: present
      tags:
        - tunnelblick

    - name: Update check automatically
      notify:
        - Kill tunnelblick
        - Start tunnelblick
      osx_defaults:
        domain: net.tunnelblick.tunnelblick
        key: updateCheckAutomatically
        type: bool
        value: '{{ tunnelblick_update_check_automatically }}'
        state: present
      tags:
        - tunnelblick

    - name: Skip dnsproblem warning
      notify:
        - Kill tunnelblick
        - Start tunnelblick
      osx_defaults:
        domain: net.tunnelblick.tunnelblick
        key: skipWarningAboutDnsProblems
        type: bool
        value: '{{ tunnelblick_skip_dnsproblem_warning }}'
        state: present
      tags:
        - tunnelblick

    - name: Skip ipnotfetched warning
      notify:
        - Kill tunnelblick
        - Start tunnelblick
      osx_defaults:
        domain: net.tunnelblick.tunnelblick
        key: skipWarningThatIPANotFetchedBeforeConnection
        type: bool
        value: '{{ tunnelblick_skip_ipnotfetched_warning }}'
        state: present
      tags:
        - tunnelblick

    - name: Skip ipchange warning
      notify:
        - Kill tunnelblick
        - Start tunnelblick
      osx_defaults:
        domain: net.tunnelblick.tunnelblick
        key: skipWarningThatIPAddressDidNotChangeAfterConnection
        type: bool
        value: '{{ tunnelblick_skip_ipchange_warning }}'
        state: present
      tags:
        - tunnelblick

    - name: Start background application
      when: tunnelblick_started
      changed_when: False
      command: open -j /Applications/Tunnelblick.app
      tags:
        - tunnelblick

...
