# Standards: 0.1
---
- name: Fact tunnelblick user
  set_fact:
    tunnelblick_user: "{{ tunnelblick_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - tunnelblick

- name: Create global directory
  loop: "{{ tunnelblick_global_configs }}"
  loop_control:
    label: "{{ item.name }}"
  file:
    path: "/Library/Application Support/Tunnelblick/Shared/{{ item.name }}.tblk/Contents/Resources"
    state: directory
    owner: root
    group: wheel
    mode: u=rwx,g=rx,o=rx
  tags:
    - tunnelblick

- name: Write global config
  loop: "{{ tunnelblick_global_configs }}"
  loop_control:
    label: "{{ item.name }}"
  template:
    src: config.j2
    dest: "/Library/Application Support/Tunnelblick/Shared/{{ item.name }}.tblk/Contents/Resources/config.ovpn"
    owner: root
    group: wheel
    mode: u=rwx,g=,o=
  tags:
    - tunnelblick

- become: "{{ (tunnelblick_user != ansible_user_id) | bool }}"
  become_user: "{{ tunnelblick_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: tunnelblick
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - tunnelblick

- name: Remove quarantine flag
  register: tunnelblick_quarantine
  failed_when: tunnelblick_quarantine.rc != 0 and "No such xattr" not in tunnelblick_quarantine.stderr
  changed_when: tunnelblick_quarantine.rc == 0
  command: xattr -d com.apple.quarantine /Applications/Tunnelblick.app
  tags:
    - tunnelblick

- become: "{{ (tunnelblick_user != ansible_user_id) | bool }}"
  become_user: "{{ tunnelblick_user }}"
  block:
    - name: Create local directory
      loop: "{{ tunnelblick_local_configs }}"
      loop_control:
        label: "{{ item.name }}"
      notify:
        - Kill tunnelblick
        - Start tunnelblick
      file:
        path: "/Users/{{ tunnelblick_user }}/Library/Application Support/Tunnelblick/Configurations/{{ item.name }}.tblk/Contents/Resources"
        state: directory
        owner: "{{ tunnelblick_user }}"
        group: staff
        mode: u=rwx,g=rx,o=
      tags:
        - tunnelblick

    - name: Write local config
      loop: "{{ tunnelblick_local_configs }}"
      loop_control:
        label: "{{ item.name }}"
      notify:
        - Kill tunnelblick
        - Start tunnelblick
      template:
        src: config.j2
        dest: "/Users/{{ tunnelblick_user }}/Library/Application Support/Tunnelblick/Configurations/{{ item.name }}.tblk/Contents/Resources/config.ovpn"
        owner: "{{ tunnelblick_user }}"
        group: staff
        mode: u=rwx,g=r,o=
      tags:
        - tunnelblick

...
