# Standards: 0.1
---
- name: Kill tunnelblick
  command: killall Tunnelblick
  register: tunnelblick_kill
  failed_when: tunnelblick_kill.rc != 0 and "No matching processes belonging to you were found" not in tunnelblick_kill.stderr
  become: "{{ (tunnelblick_user != ansible_user_id) | bool }}"
  become_user: "{{ tunnelblick_user }}"

- name: Start tunnelblick
  when: tunnelblick_started
  command: open -j /Applications/Tunnelblick.app
  become: "{{ (tunnelblick_user != ansible_user_id) | bool }}"
  become_user: "{{ tunnelblick_user }}"

...
